CREATE TABLE IF NOT EXISTS graphs (
  id INTEGER PRIMARY KEY,
  num_nodes INTEGER NOT NULL,
  edges_json TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL DEFAULT NULL
)
