CREATE TABLE IF NOT EXISTS graphs (
  id INTEGER PRIMARY KEY,
  num_nodes INTEGER NOT NULL,
  edges_json TEXT NOT NULL,
  best_time_ms INTEGER NULL DEFAULT NULL,
  cycle_found BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY,
  rating INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL DEFAULT NULL
);

INSERT INTO users (id, rating) VALUES (1, 100);
